spring:
  application:
    name: ElectorAI
  datasource:
    url: jdbc:sqlite:SQL/SQLelevator.db
    driver-class-name: org.sqlite.JDBC
    username: root
    password:
  sql:
    init:
      mode: never
  config:
    import: "optional:file:.env"

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        model: DeepSeek-R1-Distill-Qwen-7B(Free)

server:
  port: 8080

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: AUTO
  mapper-locations: classpath*:mapper/*.xml

  spring:
    devtools:
      restart:
        enabled: true
        additional-paths: src/main/java
        exclude: static/**,public/**,templates/**,log/**
        jackson:
          property-naming-strategy: SNAKE_CASE
