spring:
  application:
    name: ElectorAI
  datasource:
    url: jdbc:sqlite:SQL/SQLelevator.db
    driver-class-name: org.sqlite.JDBC
    username: root
    password:
  sql:
    init:
      mode: never

  ai:
    openai:
      api-key: s
      base-url: https://api.deepseek.com
      chat:
        options:
          model: deepseek-chat
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: static/**,public/**,templates/**,log/**
  jackson:
    property-naming-strategy: SNAKE_CASE

server:
  port: 8080

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: AUTO
  mapper-locations: classpath*:mapper/*.xml
