spring:
  application:
    name: ElectorAI
  datasource:
    url: jdbc:mysql://10.181.198.148:3306/elevator?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: user
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  ai:
    openai:
      api-key: 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
      chat-model:
        model: deepseek-chat

server:
  port: 8080

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:mapper/*.xml

  spring:
    devtools:
      restart:
        enabled: true
        additional-paths: src/main/java
        exclude: static/**,public/**,templates/**,log/**
        jackson:
          property-naming-strategy: SNAKE_CASE
