spring:
  application:
    name: ElectorAI
  datasource:
    url: jdbc:sqlite:SQL/SQLelevator.db
    driver-class-name: org.sqlite.JDBC
    username: root
    password:
    hikari:
      maximum-pool-size: 10         # 最大连接池大小
      minimum-idle: 5              # 最小空闲连接数
      idle-timeout: 30000          # 空闲连接超时（毫秒）
      max-lifetime: 1800000        # 连接最大生命周期（毫秒）
  sql:
    init:
      mode: never

  ai:
    openai:
      api-key: sk-be78f7e5e1f74f478d49a6636aa2b3ea
      base-url: https://api.deepseek.com
      chat:
        options:
          model: deepseek-chat
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: static/**,public/**,templates/**,log/**
  jackson:
    property-naming-strategy: SNAKE_CASE

server:
  port: 8080

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: AUTO
  mapper-locations: classpath*:mapper/*.xml

jwt:
  secret: Netlibata
  expirationMs: 86400000

logging:
  level:
    root: info
    com.example.goodlearnai: debug
