spring:
  application:
    name: ElectorAI
  datasource:
   # url: jdbc:mysql://10.181.198.148:3306/elevator?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
   # username: user
   # password:
   # driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:sqlite:SQL/SQLelevator.db
    driver-class-name: org.sqlite.JDBC
    username: root
    password:
  sql:
    init:
      mode: never


  ai:
    openai:
      api-key:
        chat-model:
        model: deepseek-chat

server:
  port: 8080

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: AUTO
  mapper-locations: classpath*:mapper/*.xml

  spring:
    devtools:
      restart:
        enabled: true
        additional-paths: src/main/java
        exclude: static/**,public/**,templates/**,log/**
        jackson:
          property-naming-strategy: SNAKE_CASE
